spring.application.name=JavaQuanLyKho
server.port=9999

# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/warehouse_management
spring.datasource.username=postgres
spring.datasource.password=pass123
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT
jwt.secret=${JWT_SECRET}
jwt.expire=${JWT_EXPIRE:86400}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Show SQL (dev)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh

#log
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

# UTF-8 encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
